// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMpZvnWBjGaDMHpk0gGNqLRg4adDa2ZTs',
    appId: '1:980103469711:web:2b4579a5d857312b456efa',
    messagingSenderId: '980103469711',
    projectId: 'social-profile-app',
    authDomain: 'social-profile-app.firebaseapp.com',
    storageBucket: 'social-profile-app.firebasestorage.app',
    measurementId: 'G-M89DKMX07S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTv7QqcqO4ZCndUnkDdDhwvoUMmiVJrA',
    appId: '1:980103469711:android:5018c1382de6f806456efa',
    messagingSenderId: '980103469711',
    projectId: 'social-profile-app',
    storageBucket: 'social-profile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrqrQq1uOSAS9Jo2OjXCq7iAeHle19K0Q',
    appId: '1:980103469711:ios:ccd26684934031f3456efa',
    messagingSenderId: '980103469711',
    projectId: 'social-profile-app',
    storageBucket: 'social-profile-app.firebasestorage.app',
    iosBundleId: 'com.example.socialProfileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrqrQq1uOSAS9Jo2OjXCq7iAeHle19K0Q',
    appId: '1:980103469711:ios:ccd26684934031f3456efa',
    messagingSenderId: '980103469711',
    projectId: 'social-profile-app',
    storageBucket: 'social-profile-app.firebasestorage.app',
    iosBundleId: 'com.example.socialProfileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMpZvnWBjGaDMHpk0gGNqLRg4adDa2ZTs',
    appId: '1:980103469711:web:dfaebf1f77d0e44a456efa',
    messagingSenderId: '980103469711',
    projectId: 'social-profile-app',
    authDomain: 'social-profile-app.firebaseapp.com',
    storageBucket: 'social-profile-app.firebasestorage.app',
    measurementId: 'G-7LSV8S438V',
  );
}
